2015-09-07 10:31:01,348 - [INFO] - from play in pool-4-thread-2 
Listening for HTTP on /0:0:0:0:0:0:0:0:9000

2015-09-07 10:31:06,906 - [INFO] - from play in play-internal-execution-context-1 
database [dedede] connected at jdbc:h2:file:dedede

2015-09-07 10:31:07,058 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:h2:file:play

2015-09-07 10:31:07,060 - [INFO] - from play in play-internal-execution-context-1 
database [user] connected at jdbc:h2:file:play

2015-09-07 10:31:07,693 - [ERROR] - from application in New I/O worker #1 


! @6ncfmaa8o - Internal server error, for (GET) [/register] ->

play.api.db.evolutions.InvalidDatabaseRevision: Database 'dedede' needs evolution![An SQL script need to be run on your database.]
	at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1$$anonfun$apply$1.apply$mcV$sp(Evolutions.scala:486) ~[play-jdbc_2.10-2.2.6.jar:2.2.6]
	at play.api.db.evolutions.EvolutionsPlugin.withLock(Evolutions.scala:507) ~[play-jdbc_2.10-2.2.6.jar:2.2.6]
	at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:461) ~[play-jdbc_2.10-2.2.6.jar:2.2.6]
	at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:459) ~[play-jdbc_2.10-2.2.6.jar:2.2.6]
	at scala.collection.immutable.List.foreach(List.scala:318) ~[scala-library.jar:na]
	at play.api.db.evolutions.EvolutionsPlugin.onStart(Evolutions.scala:459) ~[play-jdbc_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at scala.collection.immutable.List.foreach(List.scala:318) ~[scala-library.jar:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:18) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$.start(Play.scala:87) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:139) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:112) ~[play_2.10-2.2.6.jar:2.2.6]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:112) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:110) ~[play_2.10-2.2.6.jar:2.2.6]
	at scala.util.Success.flatMap(Try.scala:200) ~[scala-library.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:110) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[play_2.10-2.2.6.jar:2.2.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library.jar:na]

2015-09-07 10:31:49,941 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:h2:file:play

2015-09-07 10:31:50,242 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2015-09-07 10:31:58,630 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:h2:file:play

2015-09-07 10:32:09,866 - [ERROR] - from com.jolbox.bonecp.hooks.AbstractConnectionHook in play-internal-execution-context-1 
Failed to obtain initial connection Sleeping for 0ms and trying again. Attempts left: 0. Exception: null.Message:ファイル "/user" を作成中にエラーが発生しました
Error while creating file "/user" [90062-172]

2015-09-07 10:32:09,873 - [ERROR] - from application in New I/O worker #1 


! @6ncfmdo8n - Internal server error, for (GET) [/] ->

play.api.Configuration$$anon$1: Configuration error[Cannot connect to database [dddn]]
	at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:92) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Configuration.reportError(Configuration.scala:570) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:252) ~[play-jdbc_2.10-2.2.6.jar:2.2.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:243) ~[play-jdbc_2.10-2.2.6.jar:2.2.6]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244) ~[scala-library.jar:na]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244) ~[scala-library.jar:na]
	at scala.collection.immutable.List.foreach(List.scala:318) ~[scala-library.jar:na]
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244) ~[scala-library.jar:na]
	at scala.collection.AbstractTraversable.map(Traversable.scala:105) ~[scala-library.jar:na]
	at play.api.db.BoneCPPlugin.onStart(DB.scala:243) ~[play-jdbc_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at scala.collection.immutable.List.foreach(List.scala:318) ~[scala-library.jar:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:18) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$.start(Play.scala:87) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:139) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:112) ~[play_2.10-2.2.6.jar:2.2.6]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:112) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:110) ~[play_2.10-2.2.6.jar:2.2.6]
	at scala.util.Success.flatMap(Try.scala:200) ~[scala-library.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:110) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[play_2.10-2.2.6.jar:2.2.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library.jar:na]
Caused by: org.h2.jdbc.JdbcSQLException: ファイル "/user" を作成中にエラーが発生しました
Error while creating file "/user" [90062-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.message.DbException.get(DbException.java:169) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.message.DbException.get(DbException.java:146) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.store.fs.FilePathDisk.createDirectory(FilePathDisk.java:262) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.store.fs.FileUtils.createDirectory(FileUtils.java:43) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.store.fs.FileUtils.createDirectories(FileUtils.java:296) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.store.fs.FileUtils.createDirectories(FileUtils.java:295) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.store.FileLock.lockFile(FileLock.java:327) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.store.FileLock.lock(FileLock.java:129) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Database.open(Database.java:557) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Database.openDatabase(Database.java:224) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Database.<init>(Database.java:219) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Engine.openSession(Engine.java:56) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Engine.openSession(Engine.java:160) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:139) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Engine.createSession(Engine.java:122) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Engine.createSession(Engine.java:28) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:313) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:105) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.Driver.connect(Driver.java:73) ~[h2-1.3.172.jar:1.3.172]
	at play.utils.ProxyDriver.connect(ProxyDriver.scala:9) ~[play_2.10-2.2.6.jar:2.2.6]
	at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[na:1.8.0_45]
	at java.sql.DriverManager.getConnection(DriverManager.java:247) ~[na:1.8.0_45]
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:363) ~[bonecp.jar:na]
	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416) ~[bonecp.jar:na]
	at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:120) ~[bonecp.jar:na]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:245) ~[play-jdbc_2.10-2.2.6.jar:2.2.6]
	... 30 common frames omitted

2015-09-07 10:33:38,972 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:h2:file:play

2015-09-07 10:33:49,988 - [ERROR] - from com.jolbox.bonecp.hooks.AbstractConnectionHook in play-internal-execution-context-1 
Failed to obtain initial connection Sleeping for 0ms and trying again. Attempts left: 0. Exception: null.Message:ファイル "/user" を作成中にエラーが発生しました
Error while creating file "/user" [90062-172]

2015-09-07 10:33:49,993 - [ERROR] - from application in New I/O worker #1 


! @6ncfmjgbh - Internal server error, for (GET) [/] ->

play.api.Configuration$$anon$1: Configuration error[Cannot connect to database [dddn]]
	at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:92) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Configuration.reportError(Configuration.scala:570) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:252) ~[play-jdbc_2.10-2.2.6.jar:2.2.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:243) ~[play-jdbc_2.10-2.2.6.jar:2.2.6]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244) ~[scala-library.jar:na]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244) ~[scala-library.jar:na]
	at scala.collection.immutable.List.foreach(List.scala:318) ~[scala-library.jar:na]
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244) ~[scala-library.jar:na]
	at scala.collection.AbstractTraversable.map(Traversable.scala:105) ~[scala-library.jar:na]
	at play.api.db.BoneCPPlugin.onStart(DB.scala:243) ~[play-jdbc_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at scala.collection.immutable.List.foreach(List.scala:318) ~[scala-library.jar:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:18) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$.start(Play.scala:87) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:139) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:112) ~[play_2.10-2.2.6.jar:2.2.6]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:112) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:110) ~[play_2.10-2.2.6.jar:2.2.6]
	at scala.util.Success.flatMap(Try.scala:200) ~[scala-library.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:110) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[play_2.10-2.2.6.jar:2.2.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library.jar:na]
Caused by: org.h2.jdbc.JdbcSQLException: ファイル "/user" を作成中にエラーが発生しました
Error while creating file "/user" [90062-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.message.DbException.get(DbException.java:169) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.message.DbException.get(DbException.java:146) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.store.fs.FilePathDisk.createDirectory(FilePathDisk.java:262) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.store.fs.FileUtils.createDirectory(FileUtils.java:43) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.store.fs.FileUtils.createDirectories(FileUtils.java:296) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.store.fs.FileUtils.createDirectories(FileUtils.java:295) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.store.FileLock.lockFile(FileLock.java:327) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.store.FileLock.lock(FileLock.java:129) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Database.open(Database.java:557) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Database.openDatabase(Database.java:224) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Database.<init>(Database.java:219) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Engine.openSession(Engine.java:56) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Engine.openSession(Engine.java:160) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:139) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Engine.createSession(Engine.java:122) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Engine.createSession(Engine.java:28) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:313) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:105) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.Driver.connect(Driver.java:73) ~[h2-1.3.172.jar:1.3.172]
	at play.utils.ProxyDriver.connect(ProxyDriver.scala:9) ~[play_2.10-2.2.6.jar:2.2.6]
	at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[na:1.8.0_45]
	at java.sql.DriverManager.getConnection(DriverManager.java:247) ~[na:1.8.0_45]
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:363) ~[bonecp.jar:na]
	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416) ~[bonecp.jar:na]
	at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:120) ~[bonecp.jar:na]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:245) ~[play-jdbc_2.10-2.2.6.jar:2.2.6]
	... 30 common frames omitted

2015-09-07 10:36:36,971 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:h2:file:play

2015-09-07 10:36:37,130 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2015-09-07 10:36:45,663 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:h2:file:play

2015-09-07 10:36:56,685 - [ERROR] - from com.jolbox.bonecp.hooks.AbstractConnectionHook in play-internal-execution-context-1 
Failed to obtain initial connection Sleeping for 0ms and trying again. Attempts left: 0. Exception: null.Message:ファイル "/user" を作成中にエラーが発生しました
Error while creating file "/user" [90062-172]

2015-09-07 10:36:56,689 - [ERROR] - from application in New I/O worker #3 


! @6ncfn46g8 - Internal server error, for (GET) [/] ->

play.api.Configuration$$anon$1: Configuration error[Cannot connect to database [dddn]]
	at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:92) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Configuration.reportError(Configuration.scala:570) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:252) ~[play-jdbc_2.10-2.2.6.jar:2.2.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:243) ~[play-jdbc_2.10-2.2.6.jar:2.2.6]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244) ~[scala-library.jar:na]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244) ~[scala-library.jar:na]
	at scala.collection.immutable.List.foreach(List.scala:318) ~[scala-library.jar:na]
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244) ~[scala-library.jar:na]
	at scala.collection.AbstractTraversable.map(Traversable.scala:105) ~[scala-library.jar:na]
	at play.api.db.BoneCPPlugin.onStart(DB.scala:243) ~[play-jdbc_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at scala.collection.immutable.List.foreach(List.scala:318) ~[scala-library.jar:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:18) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$.start(Play.scala:87) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:139) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:112) ~[play_2.10-2.2.6.jar:2.2.6]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:112) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:110) ~[play_2.10-2.2.6.jar:2.2.6]
	at scala.util.Success.flatMap(Try.scala:200) ~[scala-library.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:110) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[play_2.10-2.2.6.jar:2.2.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library.jar:na]
Caused by: org.h2.jdbc.JdbcSQLException: ファイル "/user" を作成中にエラーが発生しました
Error while creating file "/user" [90062-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.message.DbException.get(DbException.java:169) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.message.DbException.get(DbException.java:146) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.store.fs.FilePathDisk.createDirectory(FilePathDisk.java:262) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.store.fs.FileUtils.createDirectory(FileUtils.java:43) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.store.fs.FileUtils.createDirectories(FileUtils.java:296) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.store.fs.FileUtils.createDirectories(FileUtils.java:295) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.store.FileLock.lockFile(FileLock.java:327) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.store.FileLock.lock(FileLock.java:129) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Database.open(Database.java:557) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Database.openDatabase(Database.java:224) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Database.<init>(Database.java:219) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Engine.openSession(Engine.java:56) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Engine.openSession(Engine.java:160) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:139) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Engine.createSession(Engine.java:122) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Engine.createSession(Engine.java:28) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:313) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:105) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.Driver.connect(Driver.java:73) ~[h2-1.3.172.jar:1.3.172]
	at play.utils.ProxyDriver.connect(ProxyDriver.scala:9) ~[play_2.10-2.2.6.jar:2.2.6]
	at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[na:1.8.0_45]
	at java.sql.DriverManager.getConnection(DriverManager.java:247) ~[na:1.8.0_45]
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:363) ~[bonecp.jar:na]
	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416) ~[bonecp.jar:na]
	at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:120) ~[bonecp.jar:na]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:245) ~[play-jdbc_2.10-2.2.6.jar:2.2.6]
	... 30 common frames omitted

2015-09-07 10:37:19,132 - [ERROR] - from application in New I/O worker #3 


! @6ncfn46g8 - Internal server error, for (GET) [/] ->

play.api.Configuration$$anon$1: Configuration error[Cannot connect to database [dddn]]
	at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:92) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Configuration.reportError(Configuration.scala:570) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:252) ~[play-jdbc_2.10-2.2.6.jar:2.2.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:243) ~[play-jdbc_2.10-2.2.6.jar:2.2.6]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244) ~[scala-library.jar:na]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244) ~[scala-library.jar:na]
	at scala.collection.immutable.List.foreach(List.scala:318) ~[scala-library.jar:na]
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244) ~[scala-library.jar:na]
	at scala.collection.AbstractTraversable.map(Traversable.scala:105) ~[scala-library.jar:na]
	at play.api.db.BoneCPPlugin.onStart(DB.scala:243) ~[play-jdbc_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at scala.collection.immutable.List.foreach(List.scala:318) ~[scala-library.jar:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:18) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$.start(Play.scala:87) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:139) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:112) ~[play_2.10-2.2.6.jar:2.2.6]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:112) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:110) ~[play_2.10-2.2.6.jar:2.2.6]
	at scala.util.Success.flatMap(Try.scala:200) ~[scala-library.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:110) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[play_2.10-2.2.6.jar:2.2.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library.jar:na]
Caused by: org.h2.jdbc.JdbcSQLException: ファイル "/user" を作成中にエラーが発生しました
Error while creating file "/user" [90062-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.message.DbException.get(DbException.java:169) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.message.DbException.get(DbException.java:146) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.store.fs.FilePathDisk.createDirectory(FilePathDisk.java:262) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.store.fs.FileUtils.createDirectory(FileUtils.java:43) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.store.fs.FileUtils.createDirectories(FileUtils.java:296) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.store.fs.FileUtils.createDirectories(FileUtils.java:295) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.store.FileLock.lockFile(FileLock.java:327) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.store.FileLock.lock(FileLock.java:129) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Database.open(Database.java:557) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Database.openDatabase(Database.java:224) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Database.<init>(Database.java:219) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Engine.openSession(Engine.java:56) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Engine.openSession(Engine.java:160) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:139) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Engine.createSession(Engine.java:122) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Engine.createSession(Engine.java:28) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:313) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:105) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.Driver.connect(Driver.java:73) ~[h2-1.3.172.jar:1.3.172]
	at play.utils.ProxyDriver.connect(ProxyDriver.scala:9) ~[play_2.10-2.2.6.jar:2.2.6]
	at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[na:1.8.0_45]
	at java.sql.DriverManager.getConnection(DriverManager.java:247) ~[na:1.8.0_45]
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:363) ~[bonecp.jar:na]
	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416) ~[bonecp.jar:na]
	at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:120) ~[bonecp.jar:na]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:245) ~[play-jdbc_2.10-2.2.6.jar:2.2.6]
	... 30 common frames omitted

2015-09-07 10:37:19,895 - [ERROR] - from application in New I/O worker #3 


! @6ncfn46g8 - Internal server error, for (GET) [/] ->

play.api.Configuration$$anon$1: Configuration error[Cannot connect to database [dddn]]
	at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:92) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Configuration.reportError(Configuration.scala:570) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:252) ~[play-jdbc_2.10-2.2.6.jar:2.2.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:243) ~[play-jdbc_2.10-2.2.6.jar:2.2.6]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244) ~[scala-library.jar:na]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244) ~[scala-library.jar:na]
	at scala.collection.immutable.List.foreach(List.scala:318) ~[scala-library.jar:na]
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244) ~[scala-library.jar:na]
	at scala.collection.AbstractTraversable.map(Traversable.scala:105) ~[scala-library.jar:na]
	at play.api.db.BoneCPPlugin.onStart(DB.scala:243) ~[play-jdbc_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at scala.collection.immutable.List.foreach(List.scala:318) ~[scala-library.jar:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:18) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$.start(Play.scala:87) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:139) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:112) ~[play_2.10-2.2.6.jar:2.2.6]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:112) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:110) ~[play_2.10-2.2.6.jar:2.2.6]
	at scala.util.Success.flatMap(Try.scala:200) ~[scala-library.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:110) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[play_2.10-2.2.6.jar:2.2.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library.jar:na]
Caused by: org.h2.jdbc.JdbcSQLException: ファイル "/user" を作成中にエラーが発生しました
Error while creating file "/user" [90062-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.message.DbException.get(DbException.java:169) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.message.DbException.get(DbException.java:146) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.store.fs.FilePathDisk.createDirectory(FilePathDisk.java:262) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.store.fs.FileUtils.createDirectory(FileUtils.java:43) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.store.fs.FileUtils.createDirectories(FileUtils.java:296) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.store.fs.FileUtils.createDirectories(FileUtils.java:295) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.store.FileLock.lockFile(FileLock.java:327) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.store.FileLock.lock(FileLock.java:129) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Database.open(Database.java:557) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Database.openDatabase(Database.java:224) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Database.<init>(Database.java:219) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Engine.openSession(Engine.java:56) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Engine.openSession(Engine.java:160) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:139) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Engine.createSession(Engine.java:122) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Engine.createSession(Engine.java:28) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:313) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:105) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.Driver.connect(Driver.java:73) ~[h2-1.3.172.jar:1.3.172]
	at play.utils.ProxyDriver.connect(ProxyDriver.scala:9) ~[play_2.10-2.2.6.jar:2.2.6]
	at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[na:1.8.0_45]
	at java.sql.DriverManager.getConnection(DriverManager.java:247) ~[na:1.8.0_45]
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:363) ~[bonecp.jar:na]
	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416) ~[bonecp.jar:na]
	at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:120) ~[bonecp.jar:na]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:245) ~[play-jdbc_2.10-2.2.6.jar:2.2.6]
	... 30 common frames omitted

2015-09-07 10:37:20,674 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:h2:file:play

2015-09-07 10:37:20,676 - [ERROR] - from com.jolbox.bonecp.hooks.AbstractConnectionHook in play-internal-execution-context-1 
Failed to obtain initial connection Sleeping for 0ms and trying again. Attempts left: 0. Exception: null.Message:不正なデータベース名: "/user/dddn/"
Invalid database name: "/user/dddn/" [90138-172]

2015-09-07 10:37:20,678 - [ERROR] - from application in New I/O worker #3 


! @6ncfn5g30 - Internal server error, for (GET) [/] ->

play.api.Configuration$$anon$1: Configuration error[Cannot connect to database [dddn]]
	at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:92) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Configuration.reportError(Configuration.scala:570) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:252) ~[play-jdbc_2.10-2.2.6.jar:2.2.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:243) ~[play-jdbc_2.10-2.2.6.jar:2.2.6]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244) ~[scala-library.jar:na]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244) ~[scala-library.jar:na]
	at scala.collection.immutable.List.foreach(List.scala:318) ~[scala-library.jar:na]
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244) ~[scala-library.jar:na]
	at scala.collection.AbstractTraversable.map(Traversable.scala:105) ~[scala-library.jar:na]
	at play.api.db.BoneCPPlugin.onStart(DB.scala:243) ~[play-jdbc_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at scala.collection.immutable.List.foreach(List.scala:318) ~[scala-library.jar:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:18) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$.start(Play.scala:87) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:139) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:112) ~[play_2.10-2.2.6.jar:2.2.6]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:112) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:110) ~[play_2.10-2.2.6.jar:2.2.6]
	at scala.util.Success.flatMap(Try.scala:200) ~[scala-library.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:110) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[play_2.10-2.2.6.jar:2.2.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library.jar:na]
Caused by: org.h2.jdbc.JdbcSQLException: 不正なデータベース名: "/user/dddn/"
Invalid database name: "/user/dddn/" [90138-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.message.DbException.get(DbException.java:169) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.message.DbException.get(DbException.java:146) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.ConnectionInfo.getName(ConnectionInfo.java:386) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Engine.openSession(Engine.java:41) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Engine.openSession(Engine.java:160) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:139) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Engine.createSession(Engine.java:122) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Engine.createSession(Engine.java:28) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:313) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:105) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.Driver.connect(Driver.java:73) ~[h2-1.3.172.jar:1.3.172]
	at play.utils.ProxyDriver.connect(ProxyDriver.scala:9) ~[play_2.10-2.2.6.jar:2.2.6]
	at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[na:1.8.0_45]
	at java.sql.DriverManager.getConnection(DriverManager.java:247) ~[na:1.8.0_45]
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:363) ~[bonecp.jar:na]
	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416) ~[bonecp.jar:na]
	at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:120) ~[bonecp.jar:na]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:245) ~[play-jdbc_2.10-2.2.6.jar:2.2.6]
	... 30 common frames omitted

2015-09-07 10:37:20,678 - [ERROR] - from application in New I/O worker #5 


! @6ncfn5g30 - Internal server error, for (GET) [/] ->

play.api.Configuration$$anon$1: Configuration error[Cannot connect to database [dddn]]
	at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:92) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Configuration.reportError(Configuration.scala:570) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:252) ~[play-jdbc_2.10-2.2.6.jar:2.2.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:243) ~[play-jdbc_2.10-2.2.6.jar:2.2.6]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244) ~[scala-library.jar:na]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244) ~[scala-library.jar:na]
	at scala.collection.immutable.List.foreach(List.scala:318) ~[scala-library.jar:na]
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244) ~[scala-library.jar:na]
	at scala.collection.AbstractTraversable.map(Traversable.scala:105) ~[scala-library.jar:na]
	at play.api.db.BoneCPPlugin.onStart(DB.scala:243) ~[play-jdbc_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at scala.collection.immutable.List.foreach(List.scala:318) ~[scala-library.jar:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:18) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$.start(Play.scala:87) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:139) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:112) ~[play_2.10-2.2.6.jar:2.2.6]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:112) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:110) ~[play_2.10-2.2.6.jar:2.2.6]
	at scala.util.Success.flatMap(Try.scala:200) ~[scala-library.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:110) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[play_2.10-2.2.6.jar:2.2.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library.jar:na]
Caused by: org.h2.jdbc.JdbcSQLException: 不正なデータベース名: "/user/dddn/"
Invalid database name: "/user/dddn/" [90138-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.message.DbException.get(DbException.java:169) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.message.DbException.get(DbException.java:146) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.ConnectionInfo.getName(ConnectionInfo.java:386) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Engine.openSession(Engine.java:41) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Engine.openSession(Engine.java:160) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:139) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Engine.createSession(Engine.java:122) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Engine.createSession(Engine.java:28) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:313) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:105) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.Driver.connect(Driver.java:73) ~[h2-1.3.172.jar:1.3.172]
	at play.utils.ProxyDriver.connect(ProxyDriver.scala:9) ~[play_2.10-2.2.6.jar:2.2.6]
	at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[na:1.8.0_45]
	at java.sql.DriverManager.getConnection(DriverManager.java:247) ~[na:1.8.0_45]
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:363) ~[bonecp.jar:na]
	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416) ~[bonecp.jar:na]
	at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:120) ~[bonecp.jar:na]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:245) ~[play-jdbc_2.10-2.2.6.jar:2.2.6]
	... 30 common frames omitted

2015-09-07 10:37:27,594 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:h2:file:play

2015-09-07 10:37:38,591 - [ERROR] - from com.jolbox.bonecp.hooks.AbstractConnectionHook in play-internal-execution-context-1 
Failed to obtain initial connection Sleeping for 0ms and trying again. Attempts left: 0. Exception: null.Message:ファイル "/user" を作成中にエラーが発生しました
Error while creating file "/user" [90062-172]

2015-09-07 10:37:38,595 - [ERROR] - from application in New I/O worker #5 


! @6ncfn6gg1 - Internal server error, for (GET) [/] ->

play.api.Configuration$$anon$1: Configuration error[Cannot connect to database [dddn]]
	at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:92) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Configuration.reportError(Configuration.scala:570) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:252) ~[play-jdbc_2.10-2.2.6.jar:2.2.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:243) ~[play-jdbc_2.10-2.2.6.jar:2.2.6]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244) ~[scala-library.jar:na]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244) ~[scala-library.jar:na]
	at scala.collection.immutable.List.foreach(List.scala:318) ~[scala-library.jar:na]
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244) ~[scala-library.jar:na]
	at scala.collection.AbstractTraversable.map(Traversable.scala:105) ~[scala-library.jar:na]
	at play.api.db.BoneCPPlugin.onStart(DB.scala:243) ~[play-jdbc_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at scala.collection.immutable.List.foreach(List.scala:318) ~[scala-library.jar:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:18) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$.start(Play.scala:87) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:139) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:112) ~[play_2.10-2.2.6.jar:2.2.6]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:112) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:110) ~[play_2.10-2.2.6.jar:2.2.6]
	at scala.util.Success.flatMap(Try.scala:200) ~[scala-library.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:110) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[play_2.10-2.2.6.jar:2.2.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library.jar:na]
Caused by: org.h2.jdbc.JdbcSQLException: ファイル "/user" を作成中にエラーが発生しました
Error while creating file "/user" [90062-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.message.DbException.get(DbException.java:169) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.message.DbException.get(DbException.java:146) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.store.fs.FilePathDisk.createDirectory(FilePathDisk.java:262) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.store.fs.FileUtils.createDirectory(FileUtils.java:43) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.store.fs.FileUtils.createDirectories(FileUtils.java:296) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.store.FileLock.lockFile(FileLock.java:327) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.store.FileLock.lock(FileLock.java:129) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Database.open(Database.java:557) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Database.openDatabase(Database.java:224) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Database.<init>(Database.java:219) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Engine.openSession(Engine.java:56) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Engine.openSession(Engine.java:160) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:139) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Engine.createSession(Engine.java:122) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Engine.createSession(Engine.java:28) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:313) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:105) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.Driver.connect(Driver.java:73) ~[h2-1.3.172.jar:1.3.172]
	at play.utils.ProxyDriver.connect(ProxyDriver.scala:9) ~[play_2.10-2.2.6.jar:2.2.6]
	at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[na:1.8.0_45]
	at java.sql.DriverManager.getConnection(DriverManager.java:247) ~[na:1.8.0_45]
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:363) ~[bonecp.jar:na]
	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416) ~[bonecp.jar:na]
	at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:120) ~[bonecp.jar:na]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:245) ~[play-jdbc_2.10-2.2.6.jar:2.2.6]
	... 30 common frames omitted

2015-09-07 10:37:38,596 - [ERROR] - from application in New I/O worker #6 


! @6ncfn6gg1 - Internal server error, for (GET) [/] ->

play.api.Configuration$$anon$1: Configuration error[Cannot connect to database [dddn]]
	at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:92) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Configuration.reportError(Configuration.scala:570) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:252) ~[play-jdbc_2.10-2.2.6.jar:2.2.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:243) ~[play-jdbc_2.10-2.2.6.jar:2.2.6]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244) ~[scala-library.jar:na]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244) ~[scala-library.jar:na]
	at scala.collection.immutable.List.foreach(List.scala:318) ~[scala-library.jar:na]
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244) ~[scala-library.jar:na]
	at scala.collection.AbstractTraversable.map(Traversable.scala:105) ~[scala-library.jar:na]
	at play.api.db.BoneCPPlugin.onStart(DB.scala:243) ~[play-jdbc_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at scala.collection.immutable.List.foreach(List.scala:318) ~[scala-library.jar:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:18) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.api.Play$.start(Play.scala:87) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:139) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:112) ~[play_2.10-2.2.6.jar:2.2.6]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:112) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:110) ~[play_2.10-2.2.6.jar:2.2.6]
	at scala.util.Success.flatMap(Try.scala:200) ~[scala-library.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:110) ~[play_2.10-2.2.6.jar:2.2.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[play_2.10-2.2.6.jar:2.2.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library.jar:na]
Caused by: org.h2.jdbc.JdbcSQLException: ファイル "/user" を作成中にエラーが発生しました
Error while creating file "/user" [90062-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.message.DbException.get(DbException.java:169) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.message.DbException.get(DbException.java:146) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.store.fs.FilePathDisk.createDirectory(FilePathDisk.java:262) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.store.fs.FileUtils.createDirectory(FileUtils.java:43) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.store.fs.FileUtils.createDirectories(FileUtils.java:296) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.store.FileLock.lockFile(FileLock.java:327) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.store.FileLock.lock(FileLock.java:129) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Database.open(Database.java:557) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Database.openDatabase(Database.java:224) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Database.<init>(Database.java:219) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Engine.openSession(Engine.java:56) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Engine.openSession(Engine.java:160) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:139) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Engine.createSession(Engine.java:122) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.Engine.createSession(Engine.java:28) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:313) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:105) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90) ~[h2-1.3.172.jar:1.3.172]
	at org.h2.Driver.connect(Driver.java:73) ~[h2-1.3.172.jar:1.3.172]
	at play.utils.ProxyDriver.connect(ProxyDriver.scala:9) ~[play_2.10-2.2.6.jar:2.2.6]
	at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[na:1.8.0_45]
	at java.sql.DriverManager.getConnection(DriverManager.java:247) ~[na:1.8.0_45]
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:363) ~[bonecp.jar:na]
	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416) ~[bonecp.jar:na]
	at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:120) ~[bonecp.jar:na]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:245) ~[play-jdbc_2.10-2.2.6.jar:2.2.6]
	... 30 common frames omitted

